// <auto-generated />
using System;
using MetricsAPI_LOG680;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricsAPI_LOG680.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240205141236_migrationAfterMerge")]
    partial class migrationAfterMerge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.ColumnActivityCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveTicketCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_ticket_count");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("column_name");

                    b.HasKey("Id");

                    b.ToTable("column_activity_count");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.FinishedItemsTimeframe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("FinishedItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("finished_items_count");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("finished_items_timeframe");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.LeadTimePerIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issue_number");

                    b.Property<int>("LeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time");

                    b.HasKey("Id");

                    b.ToTable("lead_time_per_issue");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.LeadTimeTimeframe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("LeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.ToTable("lead_time_timeframe");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.PRDiscussions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Comments")
                        .HasColumnType("integer")
                        .HasColumnName("comments");

                    b.Property<string>("PrId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pr_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<int>("ReviewRequests")
                        .HasColumnType("integer")
                        .HasColumnName("reviewRequests");

                    b.Property<int>("Reviews")
                        .HasColumnType("integer")
                        .HasColumnName("reviews");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_date");

                    b.Property<int>("TotalDiscussions")
                        .HasColumnType("integer")
                        .HasColumnName("totalDiscussions");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("PRDiscussions");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.PRFlowRatio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosedPR")
                        .HasColumnType("integer")
                        .HasColumnName("closedPR");

                    b.Property<double>("FlowRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("flowRatio");

                    b.Property<int>("OpenedPR")
                        .HasColumnType("integer")
                        .HasColumnName("openedPR");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("PRFlowRatio");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.PRLeadTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<TimeSpan>("LeadTime")
                        .HasColumnType("interval")
                        .HasColumnName("lead_time");

                    b.Property<string>("PrId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pr_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("PRLeadTime");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.PRMergedTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("MergedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_date");

                    b.Property<TimeSpan>("MergedTime")
                        .HasColumnType("interval")
                        .HasColumnName("merged_time");

                    b.Property<string>("PrId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pr_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("PRMergedTime");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.PRSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<string>("PrId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pr_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_date");

                    b.Property<int>("TotalChanges")
                        .HasColumnType("integer")
                        .HasColumnName("totalChanges");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("PRSize");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("A_faire_items")
                        .HasColumnType("integer")
                        .HasColumnName("a_faire_items");

                    b.Property<int>("Backlog_items")
                        .HasColumnType("integer")
                        .HasColumnName("backlog_items");

                    b.Property<int>("En_cours_items")
                        .HasColumnType("integer")
                        .HasColumnName("en_cours_items");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Project_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<string>("Repository_name")
                        .HasColumnType("text")
                        .HasColumnName("repository_name");

                    b.Property<int>("Revue_items")
                        .HasColumnType("integer")
                        .HasColumnName("revue_items");

                    b.Property<int>("Terminee_items")
                        .HasColumnType("integer")
                        .HasColumnName("terminee_items");

                    b.Property<DateTime>("Timestamps")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Total_items")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id");

                    b.ToTable("snapshots");
                });

            modelBuilder.Entity("MetricsAPI_LOG680.DTO.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("todo_items");
                });
#pragma warning restore 612, 618
        }
    }
}
