apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-ingress
  annotations:
#    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/user02eq2/metrics(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: metrics-service
            port:
              number: 80